x-app: &app
  restart: unless-stopped

services:
  web:
    image: ghcr.io/anastasiia1101/visitor-counter:${IMAGE_TAG:-latest}
    <<: *app
    environment:
      - DATABASE_URL=sqlite:////data/visitors.db
    volumes:
      - visitor-data:/data

volumes:
  visitor-data:
